const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',


    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',


    FETCH_ROLES_SUCCESS: 'FETCH_ROLES_SUCCESS',
    FETCH_ROLES_FAILED: 'FETCH_ROLES_FAILED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',


    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',


    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

    SAVE_DETAILED_DOCTOR_SUCCESS: 'SAVE_DETAILED_DOCTOR_SUCCESS',
    SAVE_DETAILED_DOCTOR_FAILED: 'SAVE_DETAILED_DOCTOR_FAILED',

    FETCH_ALL_MARKDOWN_SUCCESS: 'FETCH_ALL_MARKDOWN_SUCCESS',
    FETCH_ALL_MARKDOWN_FAILED: 'FETCH_ALL_MARKDOWN_FAILED',


    FETCH_A_DOCTOR_SUCCESS: 'FETCH_A_DOCTOR_SUCCESS',
    FETCH_A_DOCTOR_FAILED: 'FETCH_A_DOCTOR_FAILED',

    FETCH_ALL_SCHEDULE_TIME_SUCCESS: 'FETCH_ALL_SCHEDULE_TIME_SUCCESS',
    FETCH_ALL_SCHEDULE_TIME_FAILED: 'FETCH_ALL_SCHEDULE_TIME_FAILED',

    // FETCH_ALL_SCHEDULE_TIME_OF_DOCTOR_BYDAY_SUCCESS: 'FETCH_ALL_SCHEDULE_TIME_OF_DOCTOR_BYDAY_SUCCESS',
    // FETCH_ALL_SCHEDULE_TIME_OF_DOCTOR_BYDAY_FAILED: 'FETCH_ALL_SCHEDULE_TIME_OF_DOCTOR_BYDAY_FAILED',

    FETCH_ALL_REQUIRED_INFOR_SUCCESS: 'FETCH_ALL_REQUIRED_INFOR_SUCCESS',
    FETCH_ALL_REQUIRED_INFOR_FAILED: 'FETCH_ALL_REQUIRED_INFOR_FAILED',

    FETCH_ALL_SPECIALTIES_SUCCESS: 'FETCH_ALL_SPECIALTIES_SUCCESS',
    FETCH_ALL_SPECIALTIES_FAILED: 'FETCH_ALL_SPECIALTIES_FAILED',


    FETCH_ALL_CLINICS_SUCCESS: 'FETCH_ALL_CLINICS_SUCCESS',
    FETCH_ALL_CLINICS_FAILED: 'FETCH_ALL_CLINICS_FAILED',
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_LOGIN_FALSE: 'USER_LOGIN_FALSE',

})

export default actionTypes;